// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OMS.Data;

#nullable disable

namespace OMS.Migrations
{
    [DbContext(typeof(OnlineLearningExamSystemContext))]
    partial class OnlineLearningExamSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExamQuestion", b =>
                {
                    b.Property<int>("Examid")
                        .HasColumnType("integer")
                        .HasColumnName("examid");

                    b.Property<int>("Questionid")
                        .HasColumnType("integer")
                        .HasColumnName("questionid");

                    b.HasKey("Examid", "Questionid");

                    b.HasIndex("Questionid");

                    b.ToTable("examquestion");
                });

            modelBuilder.Entity("OMS.Models.Entities.Choice", b =>
                {
                    b.Property<int>("Choiceid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("choiceid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Choiceid"));

                    b.Property<string>("Choicetext")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("choicetext");

                    b.Property<bool>("Iscorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("iscorrect");

                    b.Property<int>("Questionid")
                        .HasColumnType("integer")
                        .HasColumnName("questionid");

                    b.HasKey("Choiceid");

                    b.HasIndex(new[] { "Questionid" }, "ix_choices_questionid");

                    b.ToTable("choices");
                });

            modelBuilder.Entity("OMS.Models.Entities.Course", b =>
                {
                    b.Property<int>("Courseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("courseid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Courseid"));

                    b.Property<string>("Coursename")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("coursename");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<bool>("Isdeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<int>("Subjectid")
                        .HasColumnType("integer")
                        .HasColumnName("subjectid");

                    b.Property<int>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.HasKey("Courseid");

                    b.HasIndex(new[] { "Isdeleted" }, "ix_courses_isdeleted");

                    b.HasIndex(new[] { "Subjectid" }, "ix_courses_subjectid");

                    b.HasIndex(new[] { "Teacherid" }, "ix_courses_teacherid");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("OMS.Models.Entities.Coursestudent", b =>
                {
                    b.Property<int>("Courseid")
                        .HasColumnType("integer")
                        .HasColumnName("courseid");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.Property<DateTime>("Enrolledat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolledat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Courseid", "Studentid");

                    b.HasIndex(new[] { "Studentid" }, "ix_cs_studentid");

                    b.ToTable("coursestudents");
                });

            modelBuilder.Entity("OMS.Models.Entities.Exam", b =>
                {
                    b.Property<int>("Examid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("examid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Examid"));

                    b.Property<bool>("Allowreview")
                        .HasColumnType("boolean")
                        .HasColumnName("allowreview");

                    b.Property<int>("Courseid")
                        .HasColumnType("integer")
                        .HasColumnName("courseid");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Createdby")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<int>("Durationminutes")
                        .HasColumnType("integer")
                        .HasColumnName("durationminutes");

                    b.Property<DateTime?>("Endtime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("endtime");

                    b.Property<bool>("Isdeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<bool>("Ispublished")
                        .HasColumnType("boolean")
                        .HasColumnName("ispublished");

                    b.Property<int>("Maxattempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("maxattempts");

                    b.Property<bool>("Requireaccesscode")
                        .HasColumnType("boolean")
                        .HasColumnName("requireaccesscode");

                    b.Property<DateTime?>("Reviewavailablefrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewavailablefrom");

                    b.Property<DateTime?>("Reviewavailableto")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewavailableto");

                    b.Property<DateTime?>("Starttime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starttime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<decimal>("Totalmarks")
                        .HasColumnType("decimal(7, 2)")
                        .HasColumnName("totalmarks");

                    b.HasKey("Examid");

                    b.HasIndex("Createdby");

                    b.HasIndex(new[] { "Courseid" }, "ix_exams_courseid");

                    b.HasIndex(new[] { "Isdeleted" }, "ix_exams_isdeleted");

                    b.HasIndex(new[] { "Ispublished" }, "ix_exams_ispublished");

                    b.HasIndex(new[] { "Requireaccesscode" }, "ix_exams_requireaccesscode");

                    b.ToTable("exams");
                });

            modelBuilder.Entity("OMS.Models.Entities.Examaccesscode", b =>
                {
                    b.Property<int>("Codeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("codeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codeid"));

                    b.Property<string>("Accesscode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("accesscode");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Createdby")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<int>("Examid")
                        .HasColumnType("integer")
                        .HasColumnName("examid");

                    b.Property<DateTime?>("Expiresat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresat");

                    b.Property<bool>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<int?>("Maxuses")
                        .HasColumnType("integer")
                        .HasColumnName("maxuses");

                    b.Property<int>("Usedcount")
                        .HasColumnType("integer")
                        .HasColumnName("usedcount");

                    b.HasKey("Codeid");

                    b.HasIndex("Createdby");

                    b.HasIndex(new[] { "Examid" }, "ix_eac_examid");

                    b.HasIndex(new[] { "Expiresat" }, "ix_eac_expiresat");

                    b.HasIndex(new[] { "Isactive" }, "ix_eac_isactive");

                    b.HasIndex(new[] { "Accesscode" }, "uq_eac_code")
                        .IsUnique();

                    b.ToTable("examaccesscodes");
                });

            modelBuilder.Entity("OMS.Models.Entities.Examattempt", b =>
                {
                    b.Property<int>("Attemptid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("attemptid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Attemptid"));

                    b.Property<int>("Examid")
                        .HasColumnType("integer")
                        .HasColumnName("examid");

                    b.Property<DateTime>("Starttime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starttime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("inprogress")
                        .HasColumnName("status");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.Property<DateTime?>("Submittime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submittime");

                    b.Property<decimal?>("Totalscore")
                        .HasColumnType("decimal(7, 2)")
                        .HasColumnName("totalscore");

                    b.Property<string>("Usedaccesscode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("usedaccesscode");

                    b.HasKey("Attemptid");

                    b.HasIndex(new[] { "Examid" }, "ix_attempt_examid");

                    b.HasIndex(new[] { "Status" }, "ix_attempt_status");

                    b.HasIndex(new[] { "Studentid" }, "ix_attempt_studentid");

                    b.ToTable("examattempts");
                });

            modelBuilder.Entity("OMS.Models.Entities.Examresult", b =>
                {
                    b.Property<int>("Resultid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("resultid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Resultid"));

                    b.Property<int>("Attemptid")
                        .HasColumnType("integer")
                        .HasColumnName("attemptid");

                    b.Property<decimal>("Finalscore")
                        .HasColumnType("decimal(7, 2)")
                        .HasColumnName("finalscore");

                    b.Property<DateTime>("Gradedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gradedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Gradedby")
                        .HasColumnType("integer")
                        .HasColumnName("gradedby");

                    b.HasKey("Resultid");

                    b.HasIndex(new[] { "Attemptid" }, "UQ__examresu__93079C1F09A332B6")
                        .IsUnique();

                    b.HasIndex(new[] { "Gradedby" }, "ix_examresults_gradedby");

                    b.ToTable("examresults");
                });

            modelBuilder.Entity("OMS.Models.Entities.Lesson", b =>
                {
                    b.Property<int>("Lessonid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lessonid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Lessonid"));

                    b.Property<string>("Attachmenturl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("attachmenturl");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("Courseid")
                        .HasColumnType("integer")
                        .HasColumnName("courseid");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<bool>("Isdeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<bool>("Ispublished")
                        .HasColumnType("boolean")
                        .HasColumnName("ispublished");

                    b.Property<int>("Lessonorder")
                        .HasColumnType("integer")
                        .HasColumnName("lessonorder");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Videourl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("videourl");

                    b.HasKey("Lessonid");

                    b.HasIndex(new[] { "Courseid" }, "ix_lessons_courseid");

                    b.HasIndex(new[] { "Isdeleted" }, "ix_lessons_isdeleted");

                    b.HasIndex(new[] { "Courseid", "Lessonorder" }, "uq_lesson_order")
                        .IsUnique();

                    b.ToTable("lessons");
                });

            modelBuilder.Entity("OMS.Models.Entities.Lessonprogress", b =>
                {
                    b.Property<int>("Lessonid")
                        .HasColumnType("integer")
                        .HasColumnName("lessonid");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.Property<DateTime?>("Completedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completedat");

                    b.Property<bool>("Iscompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("iscompleted");

                    b.HasKey("Lessonid", "Studentid");

                    b.HasIndex(new[] { "Studentid" }, "ix_lp_studentid");

                    b.ToTable("lessonprogress");
                });

            modelBuilder.Entity("OMS.Models.Entities.Question", b =>
                {
                    b.Property<int>("Questionid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("questionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Questionid"));

                    b.Property<int>("Courseid")
                        .HasColumnType("integer")
                        .HasColumnName("courseid");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Createdby")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<bool>("Isdeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<decimal>("Marks")
                        .HasColumnType("decimal(7, 2)")
                        .HasColumnName("marks");

                    b.Property<string>("Questioncontent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("questioncontent");

                    b.Property<string>("Questiontype")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("questiontype");

                    b.HasKey("Questionid");

                    b.HasIndex("Createdby");

                    b.HasIndex(new[] { "Courseid" }, "ix_questions_courseid");

                    b.HasIndex(new[] { "Isdeleted" }, "ix_questions_isdeleted");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("OMS.Models.Entities.Refreshtoken", b =>
                {
                    b.Property<long>("Tokenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tokenid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Tokenid"));

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Createdbyip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("createdbyip");

                    b.Property<DateTime>("Expiresat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresat");

                    b.Property<string>("Jwtid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("jwtid");

                    b.Property<string>("Replacedbytoken")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("replacedbytoken");

                    b.Property<DateTime?>("Revokedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revokedat");

                    b.Property<string>("Revokedbyip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("revokedbyip");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("token");

                    b.Property<string>("Useragent")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("useragent");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Tokenid");

                    b.HasIndex(new[] { "Expiresat" }, "ix_refreshtokens_expiresat");

                    b.HasIndex(new[] { "Userid" }, "ix_refreshtokens_userid");

                    b.HasIndex(new[] { "Token" }, "ux_refreshtokens_token")
                        .IsUnique();

                    b.ToTable("refreshtokens");
                });

            modelBuilder.Entity("OMS.Models.Entities.Role", b =>
                {
                    b.Property<int>("Roleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("roleid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Roleid"));

                    b.Property<string>("Rolename")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rolename");

                    b.HasKey("Roleid");

                    b.HasIndex(new[] { "Rolename" }, "UQ__roles__4685A0620D799878")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("OMS.Models.Entities.Studentanswer", b =>
                {
                    b.Property<int>("Answerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("answerid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Answerid"));

                    b.Property<int>("Attemptid")
                        .HasColumnType("integer")
                        .HasColumnName("attemptid");

                    b.Property<string>("Essayanswer")
                        .HasColumnType("text")
                        .HasColumnName("essayanswer");

                    b.Property<int>("Questionid")
                        .HasColumnType("integer")
                        .HasColumnName("questionid");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(7, 2)")
                        .HasColumnName("score");

                    b.Property<int?>("Selectedchoiceid")
                        .HasColumnType("integer")
                        .HasColumnName("selectedchoiceid");

                    b.HasKey("Answerid");

                    b.HasIndex("Selectedchoiceid");

                    b.HasIndex(new[] { "Attemptid" }, "ix_studentanswers_attemptid");

                    b.HasIndex(new[] { "Questionid" }, "ix_studentanswers_questionid");

                    b.HasIndex(new[] { "Attemptid", "Questionid" }, "ux_studentanswers_attempt_question")
                        .IsUnique();

                    b.ToTable("studentanswers");
                });

            modelBuilder.Entity("OMS.Models.Entities.Subject", b =>
                {
                    b.Property<int>("Subjectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("subjectid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Subjectid"));

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<bool>("Isdeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Subjectname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subjectname");

                    b.HasKey("Subjectid");

                    b.HasIndex(new[] { "Isdeleted" }, "ix_subjects_isdeleted");

                    b.HasIndex(new[] { "Subjectname" }, "uq_subjects_name")
                        .IsUnique();

                    b.ToTable("subjects");
                });

            modelBuilder.Entity("OMS.Models.Entities.User", b =>
                {
                    b.Property<int>("Userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Userid"));

                    b.Property<string>("Avatarurl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("avatarurl");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fullname");

                    b.Property<bool>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("passwordhash");

                    b.Property<int>("Roleid")
                        .HasColumnType("integer")
                        .HasColumnName("roleid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Userid");

                    b.HasIndex(new[] { "Roleid" }, "ix_users_roleid");

                    b.HasIndex(new[] { "Email" }, "uq_users_email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "uq_users_username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("ExamQuestion", b =>
                {
                    b.HasOne("OMS.Models.Entities.Exam", null)
                        .WithMany()
                        .HasForeignKey("Examid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMS.Models.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("Questionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OMS.Models.Entities.Choice", b =>
                {
                    b.HasOne("OMS.Models.Entities.Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("Questionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_choices_question");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OMS.Models.Entities.Course", b =>
                {
                    b.HasOne("OMS.Models.Entities.Subject", "Subject")
                        .WithMany("Courses")
                        .HasForeignKey("Subjectid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OMS.Models.Entities.User", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("Teacherid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("OMS.Models.Entities.Coursestudent", b =>
                {
                    b.HasOne("OMS.Models.Entities.Course", "Course")
                        .WithMany("Coursestudents")
                        .HasForeignKey("Courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMS.Models.Entities.User", "Student")
                        .WithMany("Coursestudents")
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OMS.Models.Entities.Exam", b =>
                {
                    b.HasOne("OMS.Models.Entities.Course", "Course")
                        .WithMany("Exams")
                        .HasForeignKey("Courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMS.Models.Entities.User", "CreatedbyNavigation")
                        .WithMany("Exams")
                        .HasForeignKey("Createdby")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CreatedbyNavigation");
                });

            modelBuilder.Entity("OMS.Models.Entities.Examaccesscode", b =>
                {
                    b.HasOne("OMS.Models.Entities.User", "CreatedbyNavigation")
                        .WithMany("Examaccesscodes")
                        .HasForeignKey("Createdby")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMS.Models.Entities.Exam", "Exam")
                        .WithMany("Examaccesscodes")
                        .HasForeignKey("Examid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedbyNavigation");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("OMS.Models.Entities.Examattempt", b =>
                {
                    b.HasOne("OMS.Models.Entities.Exam", "Exam")
                        .WithMany("Examattempts")
                        .HasForeignKey("Examid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMS.Models.Entities.User", "Student")
                        .WithMany("Examattempts")
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OMS.Models.Entities.Examresult", b =>
                {
                    b.HasOne("OMS.Models.Entities.Examattempt", "Attempt")
                        .WithOne("Examresult")
                        .HasForeignKey("OMS.Models.Entities.Examresult", "Attemptid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMS.Models.Entities.User", "GradedbyNavigation")
                        .WithMany("Examresults")
                        .HasForeignKey("Gradedby")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("GradedbyNavigation");
                });

            modelBuilder.Entity("OMS.Models.Entities.Lesson", b =>
                {
                    b.HasOne("OMS.Models.Entities.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("Courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("OMS.Models.Entities.Lessonprogress", b =>
                {
                    b.HasOne("OMS.Models.Entities.Lesson", "Lesson")
                        .WithMany("Lessonprogresses")
                        .HasForeignKey("Lessonid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMS.Models.Entities.User", "Student")
                        .WithMany("Lessonprogresses")
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OMS.Models.Entities.Question", b =>
                {
                    b.HasOne("OMS.Models.Entities.Course", "Course")
                        .WithMany("Questions")
                        .HasForeignKey("Courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMS.Models.Entities.User", "CreatedbyNavigation")
                        .WithMany("Questions")
                        .HasForeignKey("Createdby")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CreatedbyNavigation");
                });

            modelBuilder.Entity("OMS.Models.Entities.Refreshtoken", b =>
                {
                    b.HasOne("OMS.Models.Entities.User", "User")
                        .WithMany("Refreshtokens")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OMS.Models.Entities.Studentanswer", b =>
                {
                    b.HasOne("OMS.Models.Entities.Examattempt", "Attempt")
                        .WithMany("Studentanswers")
                        .HasForeignKey("Attemptid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMS.Models.Entities.Question", "Question")
                        .WithMany("Studentanswers")
                        .HasForeignKey("Questionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMS.Models.Entities.Choice", "Selectedchoice")
                        .WithMany("Studentanswers")
                        .HasForeignKey("Selectedchoiceid");

                    b.Navigation("Attempt");

                    b.Navigation("Question");

                    b.Navigation("Selectedchoice");
                });

            modelBuilder.Entity("OMS.Models.Entities.User", b =>
                {
                    b.HasOne("OMS.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("Roleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OMS.Models.Entities.Choice", b =>
                {
                    b.Navigation("Studentanswers");
                });

            modelBuilder.Entity("OMS.Models.Entities.Course", b =>
                {
                    b.Navigation("Coursestudents");

                    b.Navigation("Exams");

                    b.Navigation("Lessons");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("OMS.Models.Entities.Exam", b =>
                {
                    b.Navigation("Examaccesscodes");

                    b.Navigation("Examattempts");
                });

            modelBuilder.Entity("OMS.Models.Entities.Examattempt", b =>
                {
                    b.Navigation("Examresult");

                    b.Navigation("Studentanswers");
                });

            modelBuilder.Entity("OMS.Models.Entities.Lesson", b =>
                {
                    b.Navigation("Lessonprogresses");
                });

            modelBuilder.Entity("OMS.Models.Entities.Question", b =>
                {
                    b.Navigation("Choices");

                    b.Navigation("Studentanswers");
                });

            modelBuilder.Entity("OMS.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("OMS.Models.Entities.Subject", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("OMS.Models.Entities.User", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Coursestudents");

                    b.Navigation("Examaccesscodes");

                    b.Navigation("Examattempts");

                    b.Navigation("Examresults");

                    b.Navigation("Exams");

                    b.Navigation("Lessonprogresses");

                    b.Navigation("Questions");

                    b.Navigation("Refreshtokens");
                });
#pragma warning restore 612, 618
        }
    }
}
