// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OMS.Data;

#nullable disable

namespace OMS.Migrations
{
    [DbContext(typeof(OnlineLearningExamSystemContext))]
    partial class OnlineLearningExamSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Examquestion", b =>
                {
                    b.Property<int>("Examid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("examid");

                    b.Property<int>("Questionid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("questionid");

                    b.HasKey("Examid", "Questionid")
                        .HasName("PK__examques__13400C718E31CCD8");

                    b.HasIndex(new[] { "Questionid" }, "ix_examquestions_questionid");

                    b.ToTable("examquestions", null, t =>
                        {
                            t.HasTrigger("trg_examquestions_update_totalmarks");
                        });
                });

            modelBuilder.Entity("OMS.Models.Entities.Choice", b =>
                {
                    b.Property<int>("Choiceid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("choiceid");

                    b.Property<string>("Choicetext")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("choicetext");

                    b.Property<bool>("Iscorrect")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iscorrect");

                    b.Property<int>("Questionid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("questionid");

                    b.HasKey("Choiceid")
                        .HasName("PK__choices__16C8B75F6987F2BB");

                    b.HasIndex(new[] { "Questionid" }, "ix_choices_questionid");

                    b.ToTable("choices");
                });

            modelBuilder.Entity("OMS.Models.Entities.Course", b =>
                {
                    b.Property<int>("Courseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("courseid");

                    b.Property<string>("Coursename")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("coursename");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedat");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<bool>("Isdeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isdeleted");

                    b.Property<int>("Subjectid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subjectid");

                    b.Property<int>("Teacherid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("teacherid");

                    b.HasKey("Courseid")
                        .HasName("PK__courses__2AAB4BC9471B9734");

                    b.HasIndex(new[] { "Isdeleted" }, "ix_courses_isdeleted");

                    b.HasIndex(new[] { "Subjectid" }, "ix_courses_subjectid");

                    b.HasIndex(new[] { "Teacherid" }, "ix_courses_teacherid");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("OMS.Models.Entities.Coursestudent", b =>
                {
                    b.Property<int>("Courseid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("courseid");

                    b.Property<int>("Studentid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("studentid");

                    b.Property<DateTime>("Enrolledat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("enrolledat")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("Courseid", "Studentid")
                        .HasName("PK__coursest__7E7A26EFA1FDA1A7");

                    b.HasIndex(new[] { "Studentid" }, "ix_cs_studentid");

                    b.ToTable("coursestudents");
                });

            modelBuilder.Entity("OMS.Models.Entities.Exam", b =>
                {
                    b.Property<int>("Examid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("examid");

                    b.Property<bool>("Allowreview")
                        .HasColumnType("INTEGER")
                        .HasColumnName("allowreview");

                    b.Property<int>("Courseid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("courseid");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("Createdby")
                        .HasColumnType("INTEGER")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedat");

                    b.Property<int>("Durationminutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("durationminutes");

                    b.Property<DateTime?>("Endtime")
                        .HasColumnType("TEXT")
                        .HasColumnName("endtime");

                    b.Property<bool>("Isdeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isdeleted");

                    b.Property<bool>("Ispublished")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ispublished");

                    b.Property<int>("Maxattempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("maxattempts");

                    b.Property<bool>("Requireaccesscode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requireaccesscode");

                    b.Property<DateTime?>("Reviewavailablefrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewavailablefrom");

                    b.Property<DateTime?>("Reviewavailableto")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewavailableto");

                    b.Property<DateTime?>("Starttime")
                        .HasColumnType("TEXT")
                        .HasColumnName("starttime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<decimal>("Totalmarks")
                        .HasColumnType("decimal(7, 2)")
                        .HasColumnName("totalmarks");

                    b.HasKey("Examid")
                        .HasName("PK__exams__A56C2E67A94BE1C6");

                    b.HasIndex("Createdby");

                    b.HasIndex(new[] { "Courseid" }, "ix_exams_courseid");

                    b.HasIndex(new[] { "Isdeleted" }, "ix_exams_isdeleted");

                    b.HasIndex(new[] { "Ispublished" }, "ix_exams_ispublished");

                    b.HasIndex(new[] { "Requireaccesscode" }, "ix_exams_requireaccesscode");

                    b.ToTable("exams", null, t =>
                        {
                            t.HasTrigger("trg_exams_publish_validate");
                        });
                });

            modelBuilder.Entity("OMS.Models.Entities.Examaccesscode", b =>
                {
                    b.Property<int>("Codeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("codeid");

                    b.Property<string>("Accesscode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("accesscode");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("Createdby")
                        .HasColumnType("INTEGER")
                        .HasColumnName("createdby");

                    b.Property<int>("Examid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("examid");

                    b.Property<DateTime?>("Expiresat")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiresat");

                    b.Property<bool>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<int?>("Maxuses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("maxuses");

                    b.Property<int>("Usedcount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usedcount");

                    b.HasKey("Codeid")
                        .HasName("PK__examacce__47F9C38CABBE8D99");

                    b.HasIndex("Createdby");

                    b.HasIndex(new[] { "Examid" }, "ix_eac_examid");

                    b.HasIndex(new[] { "Expiresat" }, "ix_eac_expiresat");

                    b.HasIndex(new[] { "Isactive" }, "ix_eac_isactive");

                    b.HasIndex(new[] { "Accesscode" }, "uq_eac_code")
                        .IsUnique();

                    b.ToTable("examaccesscodes");
                });

            modelBuilder.Entity("OMS.Models.Entities.Examattempt", b =>
                {
                    b.Property<int>("Attemptid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("attemptid");

                    b.Property<int>("Examid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("examid");

                    b.Property<DateTime>("Starttime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("starttime")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("inprogress")
                        .HasColumnName("status");

                    b.Property<int>("Studentid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("studentid");

                    b.Property<DateTime?>("Submittime")
                        .HasColumnType("TEXT")
                        .HasColumnName("submittime");

                    b.Property<decimal?>("Totalscore")
                        .HasColumnType("decimal(7, 2)")
                        .HasColumnName("totalscore");

                    b.Property<string>("Usedaccesscode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("usedaccesscode");

                    b.HasKey("Attemptid")
                        .HasName("PK__examatte__93079C1E5CEF0DC2");

                    b.HasIndex(new[] { "Examid" }, "ix_attempt_examid");

                    b.HasIndex(new[] { "Status" }, "ix_attempt_status");

                    b.HasIndex(new[] { "Studentid" }, "ix_attempt_studentid");

                    b.ToTable("examattempts", null, t =>
                        {
                            t.HasTrigger("trg_examattempts_enforce_maxattempts");
                        });
                });

            modelBuilder.Entity("OMS.Models.Entities.Examresult", b =>
                {
                    b.Property<int>("Resultid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("resultid");

                    b.Property<int>("Attemptid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attemptid");

                    b.Property<decimal>("Finalscore")
                        .HasColumnType("decimal(7, 2)")
                        .HasColumnName("finalscore");

                    b.Property<DateTime>("Gradedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("gradedat")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("Gradedby")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gradedby");

                    b.HasKey("Resultid")
                        .HasName("PK__examresu__C6EBD0433EC3794D");

                    b.HasIndex(new[] { "Attemptid" }, "UQ__examresu__93079C1F09A332B6")
                        .IsUnique();

                    b.HasIndex(new[] { "Gradedby" }, "ix_examresults_gradedby");

                    b.ToTable("examresults");
                });

            modelBuilder.Entity("OMS.Models.Entities.Lesson", b =>
                {
                    b.Property<int>("Lessonid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("lessonid");

                    b.Property<string>("Attachmenturl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("attachmenturl");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<int>("Courseid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("courseid");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedat");

                    b.Property<bool>("Isdeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isdeleted");

                    b.Property<bool>("Ispublished")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ispublished");

                    b.Property<int>("Lessonorder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lessonorder");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Videourl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("videourl");

                    b.HasKey("Lessonid")
                        .HasName("PK__lessons__F88B935051A31C27");

                    b.HasIndex(new[] { "Courseid" }, "ix_lessons_courseid");

                    b.HasIndex(new[] { "Isdeleted" }, "ix_lessons_isdeleted");

                    b.HasIndex(new[] { "Courseid", "Lessonorder" }, "uq_lesson_order")
                        .IsUnique();

                    b.ToTable("lessons");
                });

            modelBuilder.Entity("OMS.Models.Entities.Lessonprogress", b =>
                {
                    b.Property<int>("Lessonid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lessonid");

                    b.Property<int>("Studentid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("studentid");

                    b.Property<DateTime?>("Completedat")
                        .HasColumnType("TEXT")
                        .HasColumnName("completedat");

                    b.Property<bool>("Iscompleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iscompleted");

                    b.HasKey("Lessonid", "Studentid")
                        .HasName("PK__lessonpr__AC5AFE76518F04CF");

                    b.HasIndex(new[] { "Studentid" }, "ix_lp_studentid");

                    b.ToTable("lessonprogress");
                });

            modelBuilder.Entity("OMS.Models.Entities.Question", b =>
                {
                    b.Property<int>("Questionid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("questionid");

                    b.Property<int>("Courseid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("courseid");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("Createdby")
                        .HasColumnType("INTEGER")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedat");

                    b.Property<bool>("Isdeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isdeleted");

                    b.Property<decimal>("Marks")
                        .HasColumnType("decimal(7, 2)")
                        .HasColumnName("marks");

                    b.Property<string>("Questioncontent")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("questioncontent");

                    b.Property<string>("Questiontype")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("questiontype");

                    b.HasKey("Questionid")
                        .HasName("PK__question__62C2216AEFD90A2D");

                    b.HasIndex("Createdby");

                    b.HasIndex(new[] { "Courseid" }, "ix_questions_courseid");

                    b.HasIndex(new[] { "Isdeleted" }, "ix_questions_isdeleted");

                    b.ToTable("questions", null, t =>
                        {
                            t.HasTrigger("trg_questions_update_totalmarks");
                        });
                });

            modelBuilder.Entity("OMS.Models.Entities.Refreshtoken", b =>
                {
                    b.Property<long>("Tokenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("tokenid");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Createdbyip")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("createdbyip");

                    b.Property<DateTime>("Expiresat")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiresat");

                    b.Property<string>("Jwtid")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("jwtid");

                    b.Property<string>("Replacedbytoken")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT")
                        .HasColumnName("replacedbytoken");

                    b.Property<DateTime?>("Revokedat")
                        .HasColumnType("TEXT")
                        .HasColumnName("revokedat");

                    b.Property<string>("Revokedbyip")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("revokedbyip");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<string>("Useragent")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("useragent");

                    b.Property<int>("Userid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("userid");

                    b.HasKey("Tokenid")
                        .HasName("PK__refresht__AC17DF2F2CE6675E");

                    b.HasIndex(new[] { "Expiresat" }, "ix_refreshtokens_expiresat");

                    b.HasIndex(new[] { "Userid" }, "ix_refreshtokens_userid");

                    b.HasIndex(new[] { "Token" }, "ux_refreshtokens_token")
                        .IsUnique();

                    b.ToTable("refreshtokens");
                });

            modelBuilder.Entity("OMS.Models.Entities.Role", b =>
                {
                    b.Property<int>("Roleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("roleid");

                    b.Property<string>("Rolename")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("rolename");

                    b.HasKey("Roleid")
                        .HasName("PK__roles__CD994BF2D0E014A6");

                    b.HasIndex(new[] { "Rolename" }, "UQ__roles__4685A0620D799878")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("OMS.Models.Entities.Studentanswer", b =>
                {
                    b.Property<int>("Answerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("answerid");

                    b.Property<int>("Attemptid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attemptid");

                    b.Property<string>("Essayanswer")
                        .HasColumnType("TEXT")
                        .HasColumnName("essayanswer");

                    b.Property<int>("Questionid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("questionid");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(7, 2)")
                        .HasColumnName("score");

                    b.Property<int?>("Selectedchoiceid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("selectedchoiceid");

                    b.HasKey("Answerid")
                        .HasName("PK__studenta__6837BD9C4E00477D");

                    b.HasIndex("Selectedchoiceid");

                    b.HasIndex(new[] { "Attemptid" }, "ix_studentanswers_attemptid");

                    b.HasIndex(new[] { "Questionid" }, "ix_studentanswers_questionid");

                    b.HasIndex(new[] { "Attemptid", "Questionid" }, "ux_studentanswers_attempt_question")
                        .IsUnique();

                    b.ToTable("studentanswers", null, t =>
                        {
                            t.HasTrigger("trg_studentanswers_validate");
                        });
                });

            modelBuilder.Entity("OMS.Models.Entities.Subject", b =>
                {
                    b.Property<int>("Subjectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("subjectid");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedat");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<bool>("Isdeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Subjectname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("subjectname");

                    b.HasKey("Subjectid")
                        .HasName("PK__subjects__ACE1437884B53055");

                    b.HasIndex(new[] { "Isdeleted" }, "ix_subjects_isdeleted");

                    b.HasIndex(new[] { "Subjectname" }, "uq_subjects_name")
                        .IsUnique();

                    b.ToTable("subjects");
                });

            modelBuilder.Entity("OMS.Models.Entities.User", b =>
                {
                    b.Property<int>("Userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("userid");

                    b.Property<string>("Avatarurl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("avatarurl");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("fullname");

                    b.Property<bool>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("passwordhash");

                    b.Property<int>("Roleid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("roleid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Userid")
                        .HasName("PK__users__CBA1B25799860EF1");

                    b.HasIndex(new[] { "Roleid" }, "ix_users_roleid");

                    b.HasIndex(new[] { "Email" }, "uq_users_email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "uq_users_username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Examquestion", b =>
                {
                    b.HasOne("OMS.Models.Entities.Exam", null)
                        .WithMany()
                        .HasForeignKey("Examid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eq_exam");

                    b.HasOne("OMS.Models.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("Questionid")
                        .IsRequired()
                        .HasConstraintName("fk_eq_question");
                });

            modelBuilder.Entity("OMS.Models.Entities.Choice", b =>
                {
                    b.HasOne("OMS.Models.Entities.Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("Questionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_choices_question");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OMS.Models.Entities.Course", b =>
                {
                    b.HasOne("OMS.Models.Entities.Subject", "Subject")
                        .WithMany("Courses")
                        .HasForeignKey("Subjectid")
                        .IsRequired()
                        .HasConstraintName("fk_courses_subject");

                    b.HasOne("OMS.Models.Entities.User", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("Teacherid")
                        .IsRequired()
                        .HasConstraintName("fk_courses_teacher");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("OMS.Models.Entities.Coursestudent", b =>
                {
                    b.HasOne("OMS.Models.Entities.Course", "Course")
                        .WithMany("Coursestudents")
                        .HasForeignKey("Courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cs_course");

                    b.HasOne("OMS.Models.Entities.User", "Student")
                        .WithMany("Coursestudents")
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cs_student");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OMS.Models.Entities.Exam", b =>
                {
                    b.HasOne("OMS.Models.Entities.Course", "Course")
                        .WithMany("Exams")
                        .HasForeignKey("Courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exams_course");

                    b.HasOne("OMS.Models.Entities.User", "CreatedbyNavigation")
                        .WithMany("Exams")
                        .HasForeignKey("Createdby")
                        .IsRequired()
                        .HasConstraintName("fk_exams_createdby");

                    b.Navigation("Course");

                    b.Navigation("CreatedbyNavigation");
                });

            modelBuilder.Entity("OMS.Models.Entities.Examaccesscode", b =>
                {
                    b.HasOne("OMS.Models.Entities.User", "CreatedbyNavigation")
                        .WithMany("Examaccesscodes")
                        .HasForeignKey("Createdby")
                        .IsRequired()
                        .HasConstraintName("fk_eac_createdby");

                    b.HasOne("OMS.Models.Entities.Exam", "Exam")
                        .WithMany("Examaccesscodes")
                        .HasForeignKey("Examid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eac_exam");

                    b.Navigation("CreatedbyNavigation");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("OMS.Models.Entities.Examattempt", b =>
                {
                    b.HasOne("OMS.Models.Entities.Exam", "Exam")
                        .WithMany("Examattempts")
                        .HasForeignKey("Examid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_exam");

                    b.HasOne("OMS.Models.Entities.User", "Student")
                        .WithMany("Examattempts")
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_student");

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OMS.Models.Entities.Examresult", b =>
                {
                    b.HasOne("OMS.Models.Entities.Examattempt", "Attempt")
                        .WithOne("Examresult")
                        .HasForeignKey("OMS.Models.Entities.Examresult", "Attemptid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_result_attempt");

                    b.HasOne("OMS.Models.Entities.User", "GradedbyNavigation")
                        .WithMany("Examresults")
                        .HasForeignKey("Gradedby")
                        .IsRequired()
                        .HasConstraintName("fk_result_gradedby");

                    b.Navigation("Attempt");

                    b.Navigation("GradedbyNavigation");
                });

            modelBuilder.Entity("OMS.Models.Entities.Lesson", b =>
                {
                    b.HasOne("OMS.Models.Entities.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("Courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_course");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("OMS.Models.Entities.Lessonprogress", b =>
                {
                    b.HasOne("OMS.Models.Entities.Lesson", "Lesson")
                        .WithMany("Lessonprogresses")
                        .HasForeignKey("Lessonid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lp_lesson");

                    b.HasOne("OMS.Models.Entities.User", "Student")
                        .WithMany("Lessonprogresses")
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lp_student");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OMS.Models.Entities.Question", b =>
                {
                    b.HasOne("OMS.Models.Entities.Course", "Course")
                        .WithMany("Questions")
                        .HasForeignKey("Courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_course");

                    b.HasOne("OMS.Models.Entities.User", "CreatedbyNavigation")
                        .WithMany("Questions")
                        .HasForeignKey("Createdby")
                        .IsRequired()
                        .HasConstraintName("fk_questions_createdby");

                    b.Navigation("Course");

                    b.Navigation("CreatedbyNavigation");
                });

            modelBuilder.Entity("OMS.Models.Entities.Refreshtoken", b =>
                {
                    b.HasOne("OMS.Models.Entities.User", "User")
                        .WithMany("Refreshtokens")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refreshtokens_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OMS.Models.Entities.Studentanswer", b =>
                {
                    b.HasOne("OMS.Models.Entities.Examattempt", "Attempt")
                        .WithMany("Studentanswers")
                        .HasForeignKey("Attemptid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sa_attempt");

                    b.HasOne("OMS.Models.Entities.Question", "Question")
                        .WithMany("Studentanswers")
                        .HasForeignKey("Questionid")
                        .IsRequired()
                        .HasConstraintName("fk_sa_question");

                    b.HasOne("OMS.Models.Entities.Choice", "Selectedchoice")
                        .WithMany("Studentanswers")
                        .HasForeignKey("Selectedchoiceid")
                        .HasConstraintName("fk_sa_choice");

                    b.Navigation("Attempt");

                    b.Navigation("Question");

                    b.Navigation("Selectedchoice");
                });

            modelBuilder.Entity("OMS.Models.Entities.User", b =>
                {
                    b.HasOne("OMS.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("Roleid")
                        .IsRequired()
                        .HasConstraintName("fk_users_role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OMS.Models.Entities.Choice", b =>
                {
                    b.Navigation("Studentanswers");
                });

            modelBuilder.Entity("OMS.Models.Entities.Course", b =>
                {
                    b.Navigation("Coursestudents");

                    b.Navigation("Exams");

                    b.Navigation("Lessons");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("OMS.Models.Entities.Exam", b =>
                {
                    b.Navigation("Examaccesscodes");

                    b.Navigation("Examattempts");
                });

            modelBuilder.Entity("OMS.Models.Entities.Examattempt", b =>
                {
                    b.Navigation("Examresult");

                    b.Navigation("Studentanswers");
                });

            modelBuilder.Entity("OMS.Models.Entities.Lesson", b =>
                {
                    b.Navigation("Lessonprogresses");
                });

            modelBuilder.Entity("OMS.Models.Entities.Question", b =>
                {
                    b.Navigation("Choices");

                    b.Navigation("Studentanswers");
                });

            modelBuilder.Entity("OMS.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("OMS.Models.Entities.Subject", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("OMS.Models.Entities.User", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Coursestudents");

                    b.Navigation("Examaccesscodes");

                    b.Navigation("Examattempts");

                    b.Navigation("Examresults");

                    b.Navigation("Exams");

                    b.Navigation("Lessonprogresses");

                    b.Navigation("Questions");

                    b.Navigation("Refreshtokens");
                });
#pragma warning restore 612, 618
        }
    }
}
